
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: referral_db
      POSTGRES_USER: referral_user
      POSTGRES_PASSWORD: referral_pass
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: ["./wait-for-it.sh", "db:5432", "--", "gunicorn", "referral_system.wsgi:application", "--bind", "0.0.0.0:8000"]

volumes:
  postgres_data:
